daeuniverse/dae

README.md
cmd/internal/subscription.go
cmd/run.go
cmd/validate.go
common/utils.go
component/outbound/dialer/alive_dialer_set.go
component/outbound/dialer/dialer.go
component/outbound/dialer_group.go
config/config.go
config/config_merger.go
control/control_plane.go
example.dae

Example:
```
include {
conf.d/*
test.dae
}
subscription {
'file://sub.d/sub1'
}
```
Content of `sub.d/sub1` is exact the content `GET` from subscription link.

feat: support include section, check_tolerance, and subscription supports file://

---

README.md
cmd/internal/subscription.go
cmd/run.go
component/outbound/filter.go
control/control_plane.go
control/dns_upstream.go
control/udp.go
go.mod
go.sum

```
subscription {
my_sub: 'https://www.example.com/subscription/link'
better: 'https://www.better.com/subscription/link'
}
group {
my_group {
filter: subtag(better, regex: '^my_') && name(keyword: netflix)
}
}
```

feat: support subscription tag and subtag filter

---

README.md
docs/getting-started/README.md
docs/getting-started/kernel-upgrade.md

Move the `Usage` section to the `Getting-started` section for a cleaner look.
```
./docs
├── getting-started
│   ├── kernel-upgrade.md
│   └── README.md
└── ...
N directories, N files
```
https://github.com/yqlbu/dae/tree/docs

doc: adopt getting-started guide

---

common/consts/ebpf.go
common/consts/routing.go
common/netutils/dns.go
common/utils.go
component/outbound/dialer/block.go
component/outbound/transport/simpleobfs/simpleobfs.go
component/outbound/transport/tls/tls.go
component/outbound/transport/ws/ws.go
component/routing/matcher_builder.go
component/routing/optimizer.go
config/config.go
config/patch.go
control/control_plane.go
control/kern/tproxy.c
control/routing_matcher_builder.go
control/tcp.go
control/tproxy_utils.go
control/udp.go
control/udp_endpoint.go
control/utils.go
go.mod
go.sum
pkg/config_parser/section.go
pkg/config_parser/walker.go
routing.md

```shell
domain(geosite:disney) -> direct(mark: 0x800)
```

feat: support to mark direct traffic

---

Dockerfile

As the title suggests, this PR is to shorten docker command user arguments by adding default `ENTRYPOINT` and 
`CMD` to Dockerfile, which is used in the CI/CD build steps.
Before
```sh
docker exec dae dae reload
```
After
```sh
docker exec dae reload
```

feat: shorten docker command arguments by leveraging CMD

---

docs/getting-started/kernel-upgrade.md

The previous guide does NOT actually work. I've tested it on a clean Debian 11 install. Hence, I proposed the following draft changes.

doc: update guide to debian-kernel-upgrade

---

example.dae

Add an example to select target nodes by tag.

doc(example.dae): add node selection by tag

---

common/netutils/dns.go
control/control_plane_core.go
control/dns_cache.go
control/dns_control.go

1. When "ipversion_prefer" is on and the domain being looked up does not have an AAAA record, NXDomain was not cached and a new lookup was required each time. It cost much time.
2. Empty answer is NXDomain, which will not be cached by downstream domain server implementation. And a new lookup would be sent to `dae` each time. It cost many connections/packets.
1. Cache NXDomain result and non-A/AAAA result.
2. Reject with 0.0.0.0/:: instead of NXDomain.

optimize: cache NXDomain and reject with 0.0.0.0/::

---

control/control_plane.go

`curl http://[2606:4700:20::681a:d1f]:80` will fail in `domain++` mode.
```
level=warning msg="handleConn: failed to dial [2606:4700:20::681a:d1f]:80: SplitHostPort: address [[2606:4700:20::681a:d1f]]:80: missing port in address"
```
Remove duplicated brackets from sniffed ipv6-like domain.
The problem disappeared after the fix.

fix: sniffed domain with brackets

---

Makefile

Cannot build dae on macOS even after `brew install llvm`.
Add `export GOOS=linux` in Makefile.

chore(Makefile): add export GOOS=linux to build on macos

---

common/utils.go
component/outbound/dialer/connectivity_check.go
component/sniffing/http.go
component/sniffing/sniffing_bench_test.go
config/config.go
config/desc.go
config/patch.go
control/control_plane.go
example.dae

`tcp_check_http_method` is the HTTP request method to `tcp_check_url`. Use 'CONNECT' by default because some server implementations bypass accounting for this kind of traffic.
```shell
global {
#...
tcp_check_http_method: CONNECT
}
```

feat: support `tcp_check_http_method`

---

common/assets/assets.go

dae should search geodata in /etc/dae first.
The same directory with config.dae will be given the highest priority for dae to search `geodata`.

patch: search geodata at same dir with config first

---

control/dns_control.go

Cache would never expire by accident.
- Add expiration check when looking up the DNS cache.
Fix #83
Related PR: https://github.com/daeuniverse/dae/pull/63/files#diff-7092e5e0724411e117b147fe12471c61569d904d911ef0f049885f9c1b4ce37eL135

fix(dns): cache would never expire caused by #63 by accident

---

common/assets/assets.go

Fix that searching geodata in incorrect directory `/etc/dae/dae/` instead of `/etc/dae/`.
Related PR #84

patch(geodata): fix incorrect geodata search path /etc/dae/dae caused by #84

---

common/consts/dns.go
component/dns/request_routing.go
component/dns/response_routing.go

Some qname matching in DNS section does not work unstablely.
- MatcherBuilder implementation used incorrect rule index, which is fixed in this PR.

fix(dns): mismatched qname matching rules

---

component/routing/optimizer.go
docs/dns.md

Support to filter geosite rules by attributes: https://github.com/v2ray/domain-list-community#attributes
Example:
```
qname(geosite:google@cn) -> alidns
```

feat: support geosite attr

---

component/routing/domain_matcher/benchmark_test.go

`component/routing/domain_matcher/benchmark_test.go` panic due to nil pointer.

fix(test): domain_matcher/benchmark_test.go

---

docs/routing.md

Set fwmark for all traffic (not only direct traffic) should be supported by #80.
Revise docs.
Related #110

docs(routing.md): revise fwmark section

---

CHANGELOGS.md

Apply minior fix.
- chore(changelogs-v0.2.0rc1): apply minor fix
NA

chore(changelogs-v0.2.0rc1): apply minor fix

---

config/config.go
config/desc.go
example.dae

`CONNECT` will cause unexpected status code for some domains, like gstatic.com.
The method name is mistaken and should be corrected to `HEAD`.
- example.dae
- desc.go
- config.go
Fix #134

fix: change default `tcp_check_http_method` from CONNECT to `HEAD`

---

pkg/config_parser/section.go

Before the fix:
```
[Jun 10 14:26:46] DEBUG rule: ip([n = 219214]) && l4proto([n = 219215]) -> proxy
[Jun 10 14:26:46] DEBUG         ip() -> <AND>
[Jun 10 14:26:46] DEBUG         l4proto() -> proxy
```
After the fix:
```
[Jun 10 14:37:05] DEBUG rule: ip([n = 219214]) && l4proto([n = 1]) -> proxy
[Jun 10 14:37:05] DEBUG         ip() -> <AND>
[Jun 10 14:37:05] DEBUG         l4proto() -> proxy
```
This problem is caused by the incorrect accumulation of `n` within the same rule.
This problem only impacts showing.
- Remove accumulation of n.

chore: fix incorrect number of routing rule stringer

---

component/dns/response_routing.go
component/outbound/dialer/connectivity_check.go
control/control_plane.go
control/kern/tproxy.c
control/routing_matcher_builder.go
control/routing_matcher_userspace.go
pkg/trie/trie.go

`domain++` triggers userspace slow IP routing. Userspace routing is implemented by reading kernel eBpf maps and almost amazing `15ms` for every IP rule. This PR optimizes it.
1. Replace matching via kernel maps with matching via trie in userspace.
1. Fix a damn critical problem in IP trie building.

optimize(routing): fix slow domain++ ip routing

---

control/kern/tproxy.c

Problem:
```
RoutingMatcherBuilder.BuildKernspace: newLpmMap: update: no space left on device
```
Problem configuration:
```
group {
premium {
filter: name(tcp1,tcp2)
policy: random
}
udp {
filter: name(udp)
policy: random
}
hktcp {
filter: name(hktcp)
policy: random
}
hkudp {
filter: name(hkudp)
policy: random
}
}
routing {
pname(NetworkManager) -> direct
pname(DELETED) -> direct
dip(DELETED) -> direct
dip(geoip:private) -> direct
dip(geoip:cn) -> direct
domain(geosite:cn) -> direct
dport(123) -> direct
ipversion(6) -> direct
dip(geoip:US) && l4proto(tcp) -> premium
dip(geoip:US) && l4proto(udp) -> udp
dip(geoip:CA) && l4proto(tcp) -> premium
dip(geoip:CA) && l4proto(udp) -> udp
!dip(geoip:cn) && l4proto(udp) -> hkudp 
fallback: hktcp 
}
```
- Enlarge MAX_LPM_SIZE 100 times from 20480 to …

fix: enlarge kernel geoip size limit

---

cmd/run.go

Raised from dae-wing. It reloads dae at start, and if at this time dae fails in listen, dae will panic.
- Add a check in the reloading procedure.

fix: should gracefully exit if failed to listen when reloading

---

common/assets/assets.go
common/consts/app.go
common/consts/ebpf.go

Allow modifying app name and assets dir name.
Fix #_[issue number]_

chore: allow to modify app name and assets dir name

---

component/outbound/dialer/socks/socks_test.go
go.mod
go.sum

Fix up `socks5` UDP problem introduced by refactor in #80 
- Upgrade softwind to fix it up. https://github.com/mzz2017/softwind/commit/c341d431c5758562cfbce8bb749cd344a98d8ed7
Related #80.
1. Only Socks5
2. Only UDP

fix(socks5): udp problem

---

component/outbound/dialer_selection_policy.go

Bad checking for this case. This image shows a situation with no parameter given.
- Check this kind of boundary in the correct way.

fix(group): policy 'fixed' parsing

---

cmd/run.go
control/control_plane.go
go.mod
go.sum

**Problem**
We may change gRPC node configuration, but the changed configuration is hard to apply due to the long connection and connection reuse feature of gRPC.
**How to reproduce**
Context is <https://github.com/daeuniverse/dae/issues/111>. (This PR does not fix it)
If we change `allow_insecure` from false to true, and reload dae; the node remains not working.
- Upgrade softwind to support to clean the grpc connection pool. <https://github.com/mzz2017/softwind/commit/5c79a9138694865dd5ddfcdaa2074f0d4d94222a>
- Call clean func before NewDialerSetFromLinks in NewControlPlane.

fix: new control plane should reset grpc conn pool cache

---

go.mod
go.sum

`allow_insecure` will cause gRPC does not work.
- Upgrade softwind to fix it. <https://github.com/mzz2017/softwind/commit/ff9bed485072378eb14bf2038026f5a506c4b48d>
Fix #111

fix/chore(grpc): allow insecure

---

config/marshal.go

Sometimes, `zero value`, like bool type value `false` should not be ignored when `marshaling`. Especially, when the default value is `true` (defined in config/config.go) and we want to set it `false`, the `false` will be marshaled as `empty` which will be derivated as `true` furtherly unexpectedly in parsing.
- Add `IgnoreZero` option for `config.Marshaller`.
Related  <https://github.com/daeuniverse/dae-wing/issues/37>.

feat(config): support IgnoreZero option for config.Marhsaller

---

component/outbound/dialer/connectivity_check.go
control/control_plane.go

#80 caused failed connectivity check, which impacts node protocols with bad UDP support like VLESS(XUDP).
In detail, it causes checking only UDP DNS connectivity.
Affected range:
1. v0.2.0rc1
2. VLESS protocol
- Enable correct TCP DNS check.

fix: bad connectivity check of dns(udp) caused by #80

---

control/kern/tproxy.c
docs/getting-started/troubleshooting.md
hack/test/insert.sh

dae will fail to load eBPF objects under the compilation of `clang-13`.
```
FATA[0022] load eBPF objects: field TproxyWanEgress: program tproxy_wan_egress: load program: argument list too long: 1617: (bf) r2 = r6: 1618: (85) call bpf_map_loo (truncated, 992 line(s) omitted)
```
- Allow defining `__UNROLL_ROUTE_LOOP` to unroll the route loop for fewer program instructions and shorter loading time. However, enabling this brings more memory occupation.
- Add a related note into `troubleshooting.md`.
- Add a `No network after dae suspend` note into `troubleshooting.md`.

chore/docs: support to unroll route loop and update troubleshooting.md

---

.github/workflows/generate-changelogs.yml
CHANGELOGS.md

Add generate-changelogs workflow; it is identical to the one we have for `daed`; 
> **Note**: Only when we design and implement `CI modularity`, will we use a single `unified` workflow to generate changelogs for future releases.
- ci: add generate-changelogs workflow
- chore(changelogs): add changelogs placeholder
As part of #156

ci: add generate-changelogs workflow

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
control/kern/tproxy.c

Use `clang-15` instead of `clang-13` and `clang-14`  to solve this problem.

fix/ci: fix argument list too lang due to `packed` and use clang-15

---

common/consts/ebpf.go
component/outbound/dialer_group.go
control/connectivity.go
control/control_plane.go
control/tcp.go
control/udp.go

If the local host has IPv6 addresses but the remote proxy does not, `dae` drops all the IPv6 traffic onto the remote proxy. This behavior impacts lots of software that does not support happy eyeballs.
In fact, if we send the domain to the remote proxy, it will re-select ip version and this problem will be resolved.
In the past, `dae` did not support domain sniffing. The developer hope to solve this problem by happy eyeballs, but now it seems that this change needs to be optimized, and only when dialing ip instead, maintain the previous behavior.
- If `dial_mode` is not `ip`, dae removes notifying the kernel program to block the unreachable triples (group, ip version, l4 protocol).
- If the `dial` target is not an ip, dae trys to fallback to another ip version to dial.
Fix #152

fix: should allow fallbacking ip version if dialing domain

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
Dockerfile
docs/dns.md
docs/getting-started/build-by-yourself.md
docs/getting-started/run-as-daemon.md

This reverts commit 962018d14b4d886a4335ce475155a62983997144.
`v2fly`'s geodata is the least problematic.

chore(geodata): change back to v2fly geodata

---

control/tcp.go

To support this feature, we need to expose the routable dialer for `dae-wing`, so that `dae-wing` can invoke `RouteDialTcp` to pull the subscription through `dae`.

chore: expose the routable dialer for dae-wing

---

control/kern/tproxy.c

Samba cannot be connected after binding dae to the LAN interface.
- Allow port `445`. It is acceptable because the smb port cannot be customized. See <https://serverfault.com/questions/1011395/access-smb-over-a-custom-port>
Fix #154

fix: samba not work

---

.github/workflows/generate-changelogs.yml

Add control on whether to export/write release changelogs to a GitHub issue.
- ci(generate-changelogs): control whether to write to issue page
NA
Successful Workflow Run: https://github.com/daeuniverse/dae/actions/runs/5430237700/jobs/9875838196

ci(generate-changelogs): add control on whether to write to issue page

---

control/dns_control.go

Non `A/AAAA` DNS lookup does not use cache. This PR fixes it.
- Remove limit `A/AAAA` from looking up the cache.

optimize(dns): cache all qtype (not only a/aaaa)

---

control/control_plane.go
control/control_plane_core.go

Sometimes, we want to bind a `LAN` interface once it is brought up (NewLink).
For example, I want to bind dae to `ap0` once I start to share my hotspot. However, I do not exactly know when in the future I will start to share my hotspot and create an `ap0`. dae will fail to start if fail to bind any LAN interfaces.
Another problem is that if my `ap0` is deleted, when `ap0` is created in the future, `dae` will not bind to it again.
This PR fixes it.
- If fail to bind due to `link not found`, wait for `RTM_NEWLINK` and bind to it.
- If a link is deleted, wait for `RTM_NEWLINK` and bind to it.

feat: support to bind to lan lazily and re-bind to lan

---

control/control_plane_core.go

This error doesn't matter, so it can be suppressed.
- Downgrade the log level of this error to `debug`.

chore: suppress LinkSubscribe error

---

.github/workflows/build.yml
.github/workflows/pr_build.yml
README.md

As part of the roadmap mentioned in #156, this PR includes proposed changes to separate `pr-based` events from the build workflow. As a result, the ONLY difference is the `trigger`. In order to move forward to achieving CI modularity, this PR is necessary.
- docs(README): add build status badge
- ci(trigger): separate pr_build from build
- ci: add run_name followed by `#pr_number - pr_title @ pr_ref:pr_sha`
- ci: add initial job to show pr context
- ci: run `build` job after `context` job
As part of #156 
Ref: https://github.com/daeuniverse/dae/actions/runs/5494674099

ci(trigger): separate pr_build from build

---

common/netutils/dns.go
common/netutils/ip46.go
common/netutils/ip46_test.go
common/utils.go
component/dns/dns.go
component/dns/function_parser.go
component/dns/request_routing.go
component/dns/response_routing.go
component/outbound/dialer/connectivity_check.go
component/outbound/dialer/socks/socks_test.go
component/outbound/dialer_group_test.go
control/control_plane.go
control/control_plane_core.go
control/dns_cache.go
control/dns_control.go
control/dns_utils.go
control/udp.go
control/udp_endpoint.go
go.mod
go.sum

`golang.org/x/net/dns/dnsmessage` has limited RFC support and slower evolution. This PR replaces it with <https://github.com/miekg/dns> to try to fix potential problems.
- Replace `golang.org/x/net/dns/dnsmessage` with <https://github.com/miekg/dns>.

refactor(dns): replace dnsmessage with miekg/dns

---

common/consts/net.go
common/netutils/dns.go
control/control_plane.go
control/dns_control.go
control/udp_endpoint.go
go.mod
go.sum

If a DNS response is too big (greater than 512 Bytes), it would be truncated. So the `unpacking` would fail.
This PR enlarges the buffer size to 2048. Hope it is not expensive.
- Enlarge DNS response buffer to `2048`.
- Upgrade `softwind` to support `pool.GetFullCap`.

fix: truncated dns resp

---

README.md

Demise `dae.v2raya.org` as it is NOT ready.
- docs(readme): remove docs url
NA

docs: demise dae.v2raya.org

---

.github/workflows/daily-build.yml

As the title suggests. Sets default cron trigger at `UTC+8 00:00AM`
- ci(daily-build): update cron schedule
NA

ci(daily-build): update cron schedule

---

common/consts/dialer.go
control/control_plane.go
control/dns_control.go
control/tcp.go
control/udp.go
control/udp_endpoint.go
go.mod
go.sum

The stuck UDP dialing would block all other UDP dialing. This causes UDP to fail to work. This PR fixes it.
Range:
1. This problem impacts all previous versions.
2. This problem only impacts UDP except DNS.
`domain++` may reroute every UDP packet, which may consume many resources and result in unexpected results.
This PR optimizes it. If a UDP connection has already been established, we shouldn't reroute it (find another outbound/dialer) while we should reuse the dialer to write a request.
- Force to give 8s timeout for TCP/UDP dialers.
- Use fine-grained lock for UDP.
- Only re-route for the new UDP connection.

fix/optimize/refactor(udp): fix potential stuck UDP and optimize reroute logic

---

.github/workflows/pr-build.yml
.github/workflows/seed-build.yml

Currently, the version of artifact binaries in `pr-build` does NOT align with the latest `head sha`. This PR refactors the `seed-build` workflow and passes `ref` as inputs to the build process. In such a way, we may input ref precisely according to different scenarios.
Build (Main) uses `${{ github.ref }}`
PR Build (Preview) uses `${{ github.event.pull_request.head.sha }}`
- ci(pr-build): use pr.head.sha instead of github.sha
- ci(seed-build): add ref as input; default is github.ref
- ci(pr-build): use ref instead of sha as input
- ci(seed-build): add pr_build inputs to differentiate type
- fix: rework commit sha parser
- ci(seed-build): add pr_number input
NA
https://github.com/daeuniverse/dae/actions/runs/5538510193/jobs/10108524157

ci(pr-build): use pr.head.sha as default ref

---

.github/workflows/pr-build.yml

Do not trigger pr-build workflow for draft PRs
- ci(pr-build): don't trigger workflow for draft PRs
NA

ci(pr-build): don't trigger workflow for draft PRs

---

control/control_plane.go
control/dns_cache.go
control/dns_control.go

1. The DNS rejection procedure now (reject with 0.0.0.0) causes some problems <https://github.com/daeuniverse/dae/issues/136>.
1. To avoid DDoS to local services like nginx listening at port 80.
- Reject DNS look-up with NX instead of 0.0.0.0.
- Do not cache DNS records if rejecting.
Fix #136 
Related #63

fix(dns): should reject with nx instead of 0.0.0.0 

---

.github/workflows/build.yml
.github/workflows/daily-build.yml
.github/workflows/pr-build.yml
.github/workflows/seed-build.yml

Integrate check runs to report build status. Replicate https://github.com/daeuniverse/daed/pull/162
Relevant workflows:
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/instantiate-check-runs/action.yml
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/report-check-run/action.yml
- https://github.com/daeuniverse/ci-seed-jobs/blob/master/core/daed/report-workflow-run/action.yml
References:
- [Github API - Check Runs](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28)
- [About GitHub status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks)
- [Github checks API vs check runs vs check …

ci/feat(build,pr-build,seed-build): integrate check runs to report build status

---

common/consts/ebpf.go
control/control_plane.go
control/control_plane_core.go
control/kern/tproxy.c

When using the dae's bind-lan functionality, the binding fails to work properly when attempting to bind a WireGuard interface. As a result, the traffic from the WireGuard interface is not being routed through the dae proxy.
See more #191.
- Support to check link type before binding to it.
- Support link type `none`.
- Refine `ebpf` code.
Closes #191.

fix: support to bind dae to wg lan (and other tun)

---

control/kern/tproxy.c

In #221, I incorrectly parse UDP header as TCP header, which causes a failure in parsing five tuples and results in bad connectivity of UDP. 
- Correct UDP parsing.
Closes #224

fix(ebpf): udp problem caused by #221 by accident

---

.github/workflows/seed-build.yml

Check out to codebase based on a given `github.sha`. This is necessary when we do future releases.
Quoted from <https://github.com/actions/checkout>
```yml
ref: ''
```
- ci(seed-build): checkout codebase based on ref
NA
NA

ci(seed-build): checkout codebase based on ref

---

component/outbound/dialer/v2ray/v2ray.go
docs/en/proxy-protocols.md
go.mod
go.sum

This PR supports network `h2` of VMess/VLESS.

feat(vmess/vless): support network h2

---

component/outbound/dialer/v2ray/cipher.go
component/outbound/dialer/v2ray/v2ray.go

We should choose chacha20-poly1305 for `vmess` users without AES hardware acceleration.

optimize(vmess): auto choose cipher instead of aes-128-gcm

---

cmd/cmd.go
common/subscription/subscription.go
config/config.go

This behavior of PR keeps in sync with dae-wing.
```
dae/<DAE_VERSION> (like v2rayA/1.0 WebRequestHelper) (like v2rayN/1.0 WebRequestHelper)
```

optimize: pull subscriptions using custom UA

---

docs/en/README.md
docs/en/proxy-protocols.md
docs/zh/README.md
example.dae

The protocol support list and alpine installation should be updated.

docs: refine protocol support and alpine installation

---

component/outbound/dialer_group.go

Should fallback to `fixed(0)` if there is only one node in this group and even if it not alive.
- Change the logic in node `select`.
N/A
N/A

optimize: force to choose one if there is only one node in the group

---

common/utils.go
component/outbound/dialer/juicity/juicity.go
go.mod
go.sum

Sometimes, we want to use a self-signed certificate without trusting it in the system. This PR implements Certificate Pinning to solve it.
See: <https://github.com/juicity/juicity/pull/61>
- Support the `pinned_certchain_sha256` param of juicity.
N/A

feat(juicity): support certificate pinning

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/seed-build.yml
control/bpf_utils.go
control/kern/tproxy.c
docs/en/troubleshooting.md
docs/en/user-guide/build-by-yourself.md

Caddy and samba cannot work.
This may be some special use of their listening socket, because `bpf_assign` returns `-94` (ESOCKTNOSUPPORT).
This problem is **NOT** about `PSH` flag of TCP.
This is most likely because the caddy port has enabled `IP_TRANSPARENT ` sockopt.
- Just accept the skb once `bpf_assign` returns -94 (ESOCKTNOSUPPORT).
Closes #261. Related #154.

fix: caddy cannot accept connections

---

component/outbound/dialer/juicity/juicity.go

Old Base64StdEncoding is not friendly for URL. This PR prefers to use Base64URLEncoding to decode the `PinnedCertchainSha256`, which was supported in <https://github.com/juicity/juicity/pull/74>.
- Try Base64URLEncoding, Base64StdEncoding and hex when decoding the `PinnedCertchainSha256`.

optimize(juicity): support Base64URLEncoding for PinnedCertchainSha256

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/seed-build.yml
Makefile
cmd/run.go
common/netutils/dns.go
component/outbound/dialer/connectivity_check.go
component/outbound/dialer/trojan/trojan.go
component/outbound/dialer/v2ray/v2ray.go
control/dns_control.go
control/tcp.go
control/udp_endpoint.go
go.mod
go.sum

- Bump quic-go to v0.37.4.
- Bump go to v1.21.
N/A

chore: upgrade quic-go to 0.37.4 to support go1.21

---

control/control_plane.go
control/control_plane_core.go

This is because link type mapping is based on `ifindex`. If the interface re-creates, its index changes, and the mapping will be invalid. This PR fixes it.
- Move the `mapLinkType` function into `_bindLan`.

fix: rebinding wg/tun not work

---

Makefile

``````shell
make BUILD_MODE='-buildmode=(build mode)'
BUILD_MODE='-buildmode=(build mode)' make
``````
I added some code in Makefile to set different BUILD_MODE values  according to different GOARCH values, so as to achieve cross-platform  compilation and position-independent executable files. This allows the  program to run on different operating systems and computing  architectures, and also improves the security of the program. This PR is to enhance the compatibility and stability of the project.
I specifically specified that only when GOARCH is amd64 or arm64,  -buildmode=pie will be used to set BUILD_MODE. This is because pie may  not be supported on other computing architectures. Therefore, I used an  ifeq statement to judge the value of GOARCH and set BUILD_MODE according to …

chore: amd64 and arm64 use PIE build mode by default

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/seed-build.yml

This PR is because [#272](https://translate.google.com/) has already selected whether to enable `-buildmode=pie` in Makefile according to GOARCH, so there is no need to specify `-buildmode=pie` in CI.

ci/chore: remove the buildmode specified in CI

---

.github/workflows/seed-build.yml
Makefile

Completely demise `buildarg=pie`.
PRs that introduce breaking changes:
- https://github.com/daeuniverse/dae/pull/272
- https://github.com/daeuniverse/dae/pull/273
- chore(make): revert to #270
- ci(seed-build): revert to 5cb7b4c 
Source: https://github.com/daeuniverse/dae/pull/270/files#diff-5cb7b4c67b5f118757a39679dac9abd4b38fbbf59b77436071adb6255ddfab7c

ci/hotfix: demise buildarg=pie

---

component/outbound/dialer/alive_dialer_set.go
component/outbound/dialer/utils.go

this PR make latencyString() shows latency like  `realLatency(+offset)` instead of `latencyAfterOffset(latencyBeforeOffset)`

optimize: latencyString shows realLatency(+offset)

---

component/outbound/dialer/alive_dialer_set.go
component/outbound/dialer/dialer.go
component/outbound/dialer/register.go
component/outbound/filter.go

print SubscriptionTag so that we can know each node is from which Subscription

feat/optimize: print SubscriptionTag in AliveDialerSet::printLatencies()

---

docs/en/README.md
docs/en/configuration/dns.md
docs/en/tutorials/run-on-macos.md
docs/zh/README.md
docs/zh/configuration/dns.md
example.dae

Since `qname` condition is more slow than `ip` condition, so the DNS example should move the `ip` condition to the start, for most DNS request, it will only need check if IP is private.
- Refine DNS example, better performance
no
no

docs: refine DNS example

---

install/shell-completion/dae
install/shell-completion/dae.bash

I am a bash user and I am not used to not having tab completion, so I made this pr

chore: add bash completion

---

install/shell-completion/dae.zsh

install:
```sh
install -m644 ./install/shell-completion/dae.zsh /usr/share/zsh/site-functions/_dae
```

chore: add zsh completion

---

cmd/cmd.go

As the title suggests. Add extra info such as Go runtime, copy-right, license to `dae --version` cmd.
- feat(cmd): extend --version print info
NA
```console
◆ dae git:(print-info) ✗ ❯❯❯ make                                                                                                                         23:25:00
-no-strip
Compiled /home/kev/Workspace/dae/control/bpf_bpfel.o
Wrote /home/kev/Workspace/dae/control/bpf_bpfel.go
Compiled /home/kev/Workspace/dae/control/bpf_bpfeb.o
Wrote /home/kev/Workspace/dae/control/bpf_bpfeb.go
-DMAX_MATCH_SET_LEN=64 -O2 -Wall -Werror
go build -o dae -trimpath -ldflags "-s -w -X github.com/daeuniverse/dae/cmd.Version=unstable-20231022.r617.7e57531 -X github.com/daeuniverse/dae/common/consts.Max
MatchSetLen_=64"  .
◆ dae git:(print-info) ✗ ❯❯❯ ./dae …
```

feat(cmd): extend --version print info

---

component/routing/domain_matcher/benchmark_test.go
go.mod
go.sum

The last fix #365 makes no sense. This PR makes up for the mistake.
Closes https://github.com/daeuniverse/daed/issues/400
Closes #367

fix: add _ into valid charset of ac machine

---

.github/workflows/kernel-test.yml

Covers IPv4 + IPv6 for TCP + UDP under WAN + LAN.
IPv6 UDP is buggy so I skipped that: #102 #387

ci: Add more kernel tests

---

control/bpf_utils.go
control/control_plane.go
control/kern/tproxy.c

Previously we call `bpf_map_lookup` constantly to fetch tproxy_pid and tproxy_port, which can be done in a more efficient way by rewriting bpf spec. This PR improves this part without any functional change.

Rewrite bpf spec before loading to avoid bpf map lookup during runtime

---

.github/workflows/docker.yml

Golang docker image has stopped the support for armv6, thus we follow it.
- Remove support for armv6 image.

ci(docker): remove support for armv6

---

.github/workflows/kernel-test.yml
control/control.go
control/control_plane.go
control/control_plane_core.go
control/kern/tproxy.c
control/tcp.go
control/udp.go
control/utils.go

Closes: #375 
废弃 tcp_dst_map，废弃 NAT 模式，全面使用 routing_tuple_map，删除兼容代码。
当前状态:
- 在我 fork 上的测试都通过 CI 了： https://github.com/jschwinger233/dae/actions/runs/7375144887/job/20066383853?pr=5
- IPv6 UDP 还有一点小问题没修，这个 PR 合并后单独修，不然 CI 又红了  - - （因为 #386 对 IPv6 UDP 是 assert failure，如果通过的话反而会挂）
- 请按照 commit review，否则 file diff 非常混乱

Use bpf_sk_assign at tproxy_wan_ingress

---

control/kern/tproxy.c

Consider two consecutive `dig @1.1.1.1 one.one.one.one`: dae will create a UDP socket binding `1.1.1.1:53` for the 1st DNS query, then by the time the 2nd one arrives at wan_egress@eth0, sk_lookup_udp will match that newly created UDP socket by mistake. 
As lookup for established UDP is not necessary at all, this PR skips that to avoid this tragedy bug.
Fixes: #383 

fix(bpf): sk_lookup_udp for listener only

---

Makefile

This PR makes dae binary statically linked:
```shell
dae $ CGO_ENABLED=1 make
-strip=/usr/bin/llvm-strip
Compiled /home/gray/src/github.com/daeuniverse/dae/control/bpf_bpfel.o
Stripped /home/gray/src/github.com/daeuniverse/dae/control/bpf_bpfel.o
Wrote /home/gray/src/github.com/daeuniverse/dae/control/bpf_bpfel.go
Compiled /home/gray/src/github.com/daeuniverse/dae/control/bpf_bpfeb.o
Stripped /home/gray/src/github.com/daeuniverse/dae/control/bpf_bpfeb.o
Wrote /home/gray/src/github.com/daeuniverse/dae/control/bpf_bpfeb.go
-DMAX_MATCH_SET_LEN=64 -O2 -Wall -Werror
go build -o dae -trimpath -ldflags "-s -w -X github.com/daeuniverse/dae/cmd.Version=unstable-20240102.r642.d69b023 -X github.com/daeuniverse/dae/common/consts.MaxMatchSetLen_=64"  .
dae $ file dae
dae: ELF 64-bit LSB executable, …
```

chore: Build statically linked binary

---

docs/en/troubleshooting.md

由于新版本（v0.5.0+）不再使用两次 NAT 方案，所以放行 port 12345 的方案无法使得防火墙放行 dae 流量。
firewalld 会拦截 reroute packets，firewalld 无法支持匹配 mark，因此只能使用 nft 来加入放行规则。
The new version (v0.5.0+) no longer uses the double NAT scheme, so the solution to allow port 12345 cannot make the firewall allow dae traffic.
Firewalld will block reroute packets. Firewalld does not support matching marks, so only NFT (nftables) can be used to add allow rules.

docs(troubleshooting.md): add firewalld related docs

---

common/consts/ebpf.go
config/config.go
control/control_plane.go
control/control_plane_core.go
docs/en/README.md
docs/zh/README.md
example.dae

```
global {
auto_config_firewall_rule: true
}
```
It performs:
```
nft list table inet firewalld && nft 'insert rule inet firewalld filter_INPUT mark & 0x08000000 == 0x08000000 accept'
```
Closes #419

feat: support to auto config firewall (firewalld)

---

cmd/run.go
control/anyfrom_pool.go
control/netns_utils.go
control/udp.go
control/utils.go

Setup an independent netns for transparent UDP socket if necessary (EADDRINUSE occurred).

fix: Workaround UDP port conflicts when another local process binds 53

---

component/outbound/dialer/connectivity_check.go
component/outbound/dialer/dialer.go
component/outbound/dialer_group_test.go
component/outbound/filter.go
control/control_plane.go
docs/en/README.md
docs/zh/README.md
example.dae

When local dns server is listening at :53 and resolv.conf points to it, the first connectivity check will fail. This is because when we use the local dns server to resolve the domain name of the node, the dae is not yet listening, but the ebpf program has been installed and dns request is redirected to dae, so the first dns request will fail.
If we add local dns servers to must_direct list, dns leaking possibly occurs.
- Activate connectivity check after listening to avoid the first failure.
- Update docs and don't add these dns servers to must_direct list.

fix/docs: fix the first check failure and possible dns leaking

---

control/anyfrom_pool.go
control/udp.go

class `Anyfrom` cache udp socket for 5 seconds, which may conflict with local dns server and make them fail in serving and listening.
- Add port 53 to whitelist and do not cache it.
Closes #412

optimize: avoid conflict with potential local dns server

---

Makefile

ci(Makefile): add back `GOARCH ?=$(shell go env GOARCH)` to enable trace module by default
https://github.com/daeuniverse/dae/issues/453#issuecomment-1925659736

ci(Makefile): enable trace module by default

---

.github/workflows/kernel-test.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/seed-build.yml
.github/workflows/sync-docs.yml

Node.js 16 is no longer supported by GitHub, we need to update the corresponding modules to a version based on Node.js 20.

ci: update ci modules using nodejs to latest

---

.github/workflows/kernel-test.yml
control/kern/tproxy.c
control/netns_utils.go

这个 PR 引入了三项针对 lan 的性能优化。先回顾 datapath：
```                              
┌──────────────────┐ 
1             │ 2                │ 
┌────┐     ┌────┼────┐      ┌───┐  │ 
│    ├─────►    │    ├──────►   │  │ 
│lan0│     │dae0│peer│      │dae│  │ 
│    ◄─────┤    │    ◄──────┤   │  │ 
└────┘     └────┼────┘      └───┘  │ 
3  │     dae netns    │ 
└──────────────────┘ 
a. bpf_lan_ingress: 做分流决策：直连流量放行进入网络栈，分流流量调用 bpf_redirect 重定向给 dae0
b. bpf_peer_ingress: 只有分流流量才可能到达这里，调用 bpf_skc_lookup 和 bpf_sk_assign 把流量指定给 dae socket
c. bpf_dae0_ingress: 只有分流流量的 **回复** 才可能到达这里，调用 bpf_redirect 把它重定向回 wan0
```
优化 1：a 和 b 处的 bpf 程序都解析了一遍二三四层的包头，其实没有必要解析两次，在 a 出解析完了之后可以通过 skb->cb 把 b 处需要知道的信息夹带过去。
优化 2：b 处的 peer_ingress bpf 没有必要对 established tcp 调用 bpf_skc_lookup 查询 socket，因为内核本身就可以完成 socket lookup。在开启 …

patch/optimize(bpf): improve lan hijack datapath performance

---

.github/workflows/lint.yml
Makefile
control/kern/tproxy.c
scripts/checkpatch.pl

No functionality change, just format bpf c code.
Also added a new github action to check code style on PR.
Kernel style guide: https://www.kernel.org/doc/html/latest/process/coding-style.html

style: format bpf c code using kernel checkpatch.pl

---

control/kern/tproxy.c

6.9 introduces https://lore.kernel.org/bpf/202402221046.020C94D@keescook/T/ which renamed bpf_lpm_trie_key to bpf_lpm_trie_key_u8, breaking CO-RE because vmlinux no longer has the definition.
This patch fixes the CO-RE issue by relying on a special cornor case that doesn't emit CO-RE relocation.
Closes #482

fix: Fix bpf CO-RE issue on 6.9

---

control/control_plane_core.go
control/kern/tproxy.c

In the commits of v0.5-v0.6, lan_egress was removed, resulting in icmpv6 redirect packets not being dropped, which forces some users (旁路由用户) to use MASQUERADE.
This PR fixed it.

fix: shoot ipv6 icmp redirects

---

control/netns_utils.go

After #458 dae doesn't rely on the majority of stack network settings. This PR removes `sysctl net.ipv6.conf.all.forwarding=1`.

fix: Don't enable net.ipv6.conf.all.forwarding

---

install/dae.service

chore(dae.service): set TimeoutStartSec=120 instead of 10

---

cmd/run.go
pkg/config_parser/section.go

In the past, not all problems would be reported when reloading, such as non-existent group name error. This PR fixes it.
Related: #470

fix: support to report all error when reloading

---

cmd/run.go
config/config.go
example.dae

This PR adds a new global config `pprof_port` to specify (and enable/disable) pprof server. Users can also enable or disable pprof on the fly using `dae reload`.

chore: Add a global config to enable pprof

---

docs/en/proxy-protocols.md
docs/zh/proxy-protocols.md

https://github.com/daeuniverse/dae/blob/cb3f69602e79ad3ff779bfed23e82f633625a5f8/docs/en/proxy-protocols.md

docs: add protocols uri schema

---

docs/en/user-guide/build-by-yourself.md

update accroding to [seed-build.yml#L105](https://github.com/daeuniverse/dae/blob/main/.github/workflows/seed-build.yml#L105) 
#559 #546 
go version should not be lower than 1.22.

docs: Update build-by-yourself.md

---

docs/en/proxy-protocols.md
docs/zh/proxy-protocols.md

docs(protocols): add hysteria2

---

docs/en/user-guide/persistent-subscription.md

Some times it may not be possible to pull the subscription when the network is poor, which can lead to users not being able to function properly if they are completely dependent on the subscription.(no node exists in the group)
Add documentation for persistent subscriptions to help users avoid this issue.

docs: persistent subscription

---

control/udp_task_pool.go

```
panic: close of closed channel
goroutine 358834 [running]:
github.com/daeuniverse/dae/control.(*UdpTaskPool).EmitTask.func1()
github.com/daeuniverse/dae/control/udp_task_pool.go:81 +0xf4
created by time.goFunc
time/sleep.go:177 +0x2d
```

fix(udp_task_pool): panic: close of closed channel

---

cmd/run.go

- run.go: Network Manager's net-online check has a bug: you'll **be** online even if you have got no IP address, so we should always check whether network is online by dae itself.

fix(cmd/run.go): always check whether network online

---

control/kern/tproxy.c

#562 caused more issues than benefits, such as #586. Unfortunately I failed to reproduce issues after several attempts. This PR reverts the changes, but introduced an alternative solution to avoid parsing packet at dae0_ingress.
~~The key idea is skbs at dae0_ingress are bound to be built from a local process (control plane process, dae), so we should be confident in using `skb->sk->{local_ip4,dst_ip4,local_ip6,dst_ip6}` to get tuples, instead of calling `parse_transport()` followed by `get_tuples()`.~~ This doesn't work because udp listener socket always has zero value as sk->dst_ip4. 
The key idea is to parse L3 by manually calling `bpf_skb_load_bytes` for twice only. The instruction number can be greatly reduced from 913 to 333 (jitted x64, kernel 6.5.0-1027-oem), -63% comparing to …

optimize(bpf): Alternative way to avoid parsing packet at dae0

---

cmd/run.go
common/utils.go
component/outbound/dialer/connectivity_check.go
config/config.go
config/desc.go
control/control_plane.go
control/dns_control.go
control/tcp.go
control/udp.go
example.dae
go.mod
go.sum

Multipath TCP or MPTCP is an extension to the standard TCP and is described in RFC 8684. It allows a device to make use of multiple interfaces at once to send and receive TCP packets over a single MPTCP connection. MPTCP can aggregate the bandwidth of multiple interfaces or prefer the one with the lowest latency.
MPTCP is support in Go 1.21
- Add MPTCP support for nodes and subscription requests
- Update config description
- Update daeuniverse/outbound to latest
Closes #595
```bash
sudo ip mptcp monitor
```

feat: add MPTCP support

---

component/outbound/dialer/connectivity_check.go
component/outbound/dialer/dialer.go
config/config.go
config/desc.go
control/control_plane.go
example.dae

此Pull Request允许group配置覆盖global配置中的节点联通性检查以支持更加灵活的场景
- 允许group段中的配置覆盖global的节点联通性检查配置
- 当group中未定义这些新的配置时，行为应当和之前完全一致
- 当group中存在这些新配置时，所有此group的dialer将会被克隆并修改联通性检查配置
Closes #619 
Archlinux
```zsh
$ uname -a
Linux secops 6.10.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 15:18:31 +0000 x86_64 GNU/Linux
```
```zsh
$ make
git submodule update --init --recursive -- trace/kern/headers && \
touch trace/kern/headers
-no-strip
Compiled /home/kagurazakanyaa/src/dae/control/bpf_bpfel.o
Wrote /home/kagurazakanyaa/src/dae/control/bpf_bpfel.go
Compiled /home/kagurazakanyaa/src/dae/control/bpf_bpfeb.o
Wrote /home/kagurazakanyaa/src/dae/control/bpf_bpfeb.go
Compiled /home/kagurazakanyaa/src/dae/trace/bpf_bpfel_x86.o
Wrote /home/kagurazakanyaa/src/dae/trace/bpf_bpfel_x86.go …
```

feat: allow group override global node connectivity check

---

docs/en/proxy-protocols.md
docs/zh/proxy-protocols.md

[The reality support for TCP protocol](https://github.com/daeuniverse/dae/pull/573) has been merged. Therefore, the documentation needs to be updated respectively.
- Add reality tcp support in ```proxy-protocols.md```

docs: add reality tcp support to proxy-protocols

---

control/kern/tproxy.c

It is better to use bitwise operators instead of arithmetic ones when merging bit fields.
- Replace C arithmetic operators with bitwise ones to improve performance

optimize: replace c arithmetic operators with bitwise ones

---

control/kern/tproxy.c

- Improve code readability of struct initialization

refactor: improve code readability of struct initialization

---

control/kern/tproxy.c

There are some redundant assignments in ```control/kern/tproxy.c```.
- Assigning the 2nd & 3rd enumeration constant by 2 and 3 is unnecessary. If an enumeration constant is not followed by ```= constant-expression```, its value is the value one greater than the value of the previous enumerator in the same enumeration.
- The variable ```ret``` is not used after being assigned.
- When ```to_read == MAX_ARG_SCANNER_BUFFER_SIZE```, the assignment is unnecessary.
- Remove redundant assignments in in ```control/kern/tproxy.c```

refactor: remove redundant assignments

---

control/kern/tproxy.c

patch: revert: refactor: improve code readability of struct initialization

---

control/kern/tproxy.c

- Fucntion ```copy_reversed_tuples()``` can be reused.
- Code is not formatted.
- Reuse function ```copy_reversed_tuples()``` & format code

refactor: reuse existing functions & format code

---

control/dns_control.go

在 PS5 上打开糖豆人会卡在启动界面，一段时间后提示网络异常，抓包显示其一直在尝试发送 api.epicgames.dev 的 DNS 请求，猜测可能是 DNS 方面的问题，对比正常配置时的 DNS 数据包，发现正常配置时，DNS 响应中的域名对应数据都是一个很短的十六进制数字且都以 C0 开头
而异常的时候，域名对应的数据都是一个完整域名的十六进制
查询资料后得知这是 DNS 协议中的压缩选项，定义在 RFC 1035 中 https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.4
所以怀疑是糖豆人客户端不兼容未压缩的 DNS 消息导致的，在修改代码开启压缩后，糖豆人正常启动，如测试结果所示，DNS 消息都正常压缩了
另外查看了国内阿里和腾讯的 DNS 都是默认开启压缩的，也就是业界是推荐默认开启压缩的，所以此改动应该不会造成兼容性问题，RFC 1305 中也提到客户端应该能解析两种格式的消息
阿里的
腾讯的
抓包数据 
[归档.zip](https://github.com/user-attachments/files/17083645/default.zip)
- fix: compatible issue when DNS msg not be compressed
Closes #338

fix: compatible issue when DNS msg not be compressed

---

component/sniffing/sniffer.go

```
level=warning msg="handleConn: %!w(<nil>): EOF"
...
```
In my opinion, these logs are quite useless.

fix(sniffer): remove useless EOF warning logs printing

---

.gitignore
cmd/run.go
common/netutils/dns.go
component/outbound/dialer/connectivity_check.go
control/dns_control.go
control/tcp.go
control/udp_endpoint_pool.go
go.mod
go.sum
pkg/logger/logger.go

Many users have reported continuous memory growth in dae, possibly due to coroutine leaks.
This phenomenon is even more obvious when the network is disconnected. A very suspicious object is that our dialer does not implement DialContext, resulting in the timeout mechanism not being triggered when calling down.
This PR attempts to fix this problem.
- Implement DialContext for dialers.
- Close misclosed underlay UDP connection for tuic/juicity.

fix: connection leaks

---

component/outbound/dialer/dialer.go
config/config.go
example.dae
go.mod
go.sum

ref: https://github.com/daeuniverse/outbound/pull/21
- Implement bandwidth config parsing in dae:
```
global {
...
bandwidth_max_tx: 26214400 # 200Mbps == 25MB/s == 26214400 B/s uplink
bandwidth_max_rx: 131072000 # 1Gbps == 125MB/s == 131072000 B/s downlink
}
```
- Improve handling for `insecure` parameter in hysteria2 URI parsing.

feat: support bandwidth configuration

---

go.mod
go.sum

Fix the problem in https://github.com/daeuniverse/outbound/commit/3905858d935f4a07632dfd5ef9067ceadb00033d.
This problem is introduced by https://github.com/daeuniverse/outbound/commit/d470a59233a522657f8af39c7e44e2d56cdec3ac.
According to <https://xtls.github.io/config/inbounds/vless.html#clientobject>, empty flow is as ordinary tls, which is allowed.

fix(vless): allow empty flow as ordinary tls

---

cmd/trace.go
trace/trace.go

#524 
Currently `dae trace` dumps huge amount of packets, most of them are not necessary. In most cases, we care about packets that are dropped by kernel, aka processed by kernel function `kfree_skb_reason`, or called by `kfree_skbmem` but without `consume_skb`.
- Add `--drop-only` option to where dae only prints the packets dropped by kernel.
- `dae trace` now print all the skbs of a packet until the packet is freed by kernel, whether it runs with `--drop-only` or not.
Closes #524 
start tracing
ffff9e800e629d00 mark=0 netns=4026531840 if=2(ens18) proc=735(/usr/bin/dae) 142.250.197.174:80 > 192.168.1.101:33334 tcp_flags=.F payload_len=0 tcp_v4_early_demux
ffff9e800e629d00 mark=0 netns=4026531840 if=2(ens18) proc=735(/usr/bin/dae) 142.250.197.174:80 > 192.168.1.101:33334 tcp_flags=.F …

feat(trace): add drop-only option

---

component/routing/domain_matcher/benchmark_test.go
config/config.go
docs/en/README.md
docs/en/configuration/dns.md
docs/en/configuration/external-dns.md
docs/en/configuration/routing.md
docs/en/configuration/separate-config.md
docs/en/tutorials/run-on-macos.md
docs/zh/README.md
docs/zh/configuration/dns.md
docs/zh/configuration/routing.md
example.dae

Since Google recommend to use dns.google as a DoH server and we are trying add DoH support, and use both of them as a UDP or TCP DNS server is equal, so we can change the default config and docs early
https://developers.google.com/speed/public-dns/docs/doh/migration?hl=zh-cn#base64url 
https://github.com/daeuniverse/dae/pull/649#issuecomment-2379577896

docs: Google DNS should use dns.google instead of dns.google.com

---

component/routing/optimizer.go

Without this patch, `mac('2c:9e:00:7a:26:38') -> proxy` followed by `!mac('2c:9e:00:7a:26:38') -> proxy` will be wrongly merged to `mac('2c:9e:00:7a:26:38') -> proxy`. 
Closes #339

fix(routing): Fix MergeAndSortRulesOptimizer

---

component/dns/dns.go
component/dns/upstream.go
control/dns.go
control/dns_control.go

dae lacks support for some encrypted DNS protocols, this PR adds support for DoH, DoT, DoH3, DoQ 
TODO
[^dohid]:  https://datatracker.ietf.org/doc/html/rfc8484#section-4.1
[^doqid]:https://www.rfc-editor.org/rfc/rfc9250.html#name-dns-message-ids
- feat: support DoH, DoT, DoH3, DoQ 
Closes #321
Closes #583
time="Sep 24 15:58:37" level=trace msg="Received UDP(DNS) 192.168.33.244:41532 <-> 192.168.33.1:53: wq.io. A"
time="Sep 24 15:58:37" level=trace msg="Request to DNS upstream" question=[{wq.io. 1 1}] upstream="tls://dns.google:853"
time="Sep 24 15:58:37" level=trace msg="Choose DNS path" choose="tcp+4" ipversions=[4 6] l4protos=[tcp] upstream="tls://dns.google:853" use="8.8.8.8:853"
time="Sep 24 15:58:37" level=trace msg=Accept question=[{wq.io. 1 1}] upstream="tls://dns.google:853" …

feat(dns): support DoH, DoT, DoH3, DoQ

---

cmd/trace.go
trace/kallsyms.go

Currently, reading kallsyms during program loading causes unnecessary high memory usage, while kallsyms is only used in the trace command. Therefore, this patch changes it to initialize kallsyms before executing the trace command.
- read kallsyms only in the trace command
```
global{ pprof_port: 12333 }
routing{}
```
Use `go tool pprof -http=:8080 http://localhost:12333/debug/pprof/heap` to generate the flame graph.
Lowers RSS usage from 194 MiB to 75 MiB.
Before:
After:

optimize: reduce memory usage by reading kallsyms only in the trace command

---

control/udp_task_pool.go
go.mod
go.sum

Dependency missing. Clear build failed.
- minimal upgrade panjf2000/ants dependency to v2.0.0
- run `go mod tidy`
Closes #701 
```
=== RUN   TestUdpTaskPool
/root/repo/github.com/daeuniverse/dae/control/udp_task_pool_test.go:20: [{"cpu":"cpu-total","user":84004.3,"system":36651.2,"idle":28526534.9,"nice":163.4,"iowait":402.9,"irq":0.0,"softirq":1131.2,"steal":0.0,"guest":0.0,"guestNice":0.0}]
/root/repo/github.com/daeuniverse/dae/control/udp_task_pool_test.go:30: [{"cpu":"cpu-total","user":84004.6,"system":36651.3,"idle":28526616.2,"nice":163.4,"iowait":402.9,"irq":0.0,"softirq":1131.2,"steal":0.0,"guest":0.0,"guestNice":0.0}]
--- PASS: TestUdpTaskPool (5.11s)
PASS
coverage: 3.7% of statements in all
ok      github.com/daeuniverse/dae/control      7.099s  coverage: 3.7% of statements in …
```

fix: minimal upgrade panjf2000/ants dependency to v2.0.0

---

docs/en/tutorials/run-on-alpine.md
docs/zh/tutorials/run-on-alpine.md

docs(run-on-alpine.md): update for Alpine's kernel changes

---

docs/en/README.md
docs/en/configuration/dns.md
docs/zh/README.md
docs/zh/configuration/dns.md

Recently cloudflare started to enable Encrypted Client Hello by default, which affects traffic split due to the inability to sniff domains.
I think it is necessary to add `qtype(https) -> reject` to docs
- Add `qtype(https) -> reject` to the configuration files in `README.md` and `dns.md`.

docs: disable Encrypted ClientHello to avoid affecting traffic split

---

control/kern/tproxy.c

bpf_map_lookup_elem返回的指针，如果进行修改，会改到elem上去，之前的代码忽略了这点
这导致match_set在触发must_rules时被修改，从而导致对其他没触发must_rules的连接也变为must，从而导致控制面不处理dns逻辑
- Fix must_rules causes entire match_set to become must.

fix: must_rules cause entire match_set to become must.

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
install/package_after_install.sh
install/package_after_remove.sh

- Currently `dae` doesn't provide linux packages, including `.deb`, `.rpm` and `.pkg.tar.zst`. Add them in prerelease & release to make installing `dae` more convenient for Linux users.
- Adopted by [Linux kernel](https://www.kernel.org) source code, `.tar.xz` provides higher compression ratio than `.zip`, which also preserves UNIX file permissions.
- Add `.deb`, `.rpm` and `.tar.zst` packages in prerelease & release workflow
- Add  `.tar.xz` format for full source archive
All packages are built successfully in my fork (`v0.9.1` is just a fake version number)

ci: add linux packages & minimize archive size

---

control/kern/tests/bpf_test.c

- Pull request #483 only fixes the CO-RE issue in production code. eBPF tests still failed when running on kernel 6.9 and above.
- Fix CO-RE issue on kernel 6.9 and above in eBPF tests
Before:
```
=== RUN   Test
bpf_test.go:72: Failed to load objects: Verifier error: load program: bad CO-RE relocation:
0: R1=ctx() R10=fp0
; int testcheck_mac_match(struct __sk_buff *skb) @ bpf_test.c:549
0: (bf) r6 = r1                       ; R1=ctx() R6_w=ctx()
1: (b7) r1 = 0                        ; R1_w=0
; struct lpm_key lpm_key = {}; @ bpf_test.c:551
2: (7b) *(u64 *)(r10 -72) = r1        ; R1_w=0 R10=fp0 fp-72_w=0
3: (7b) *(u64 *)(r10 -80) = r1        ; R1_w=0 R10=fp0 fp-80_w=0
4: (bf) r2 = r10                      ; R2_w=fp0 R10=fp0
;  @ bpf_test.c:0
5: (07) r2 += -80 …
```

test: fix CO-RE issue on kernel 6.9 and above in eBPF tests

---

cmd/internal/su.go
cmd/reload.go
cmd/run.go
cmd/sysdump.go
control/dns_control.go
trace/trace.go

我查看代码发现 cmd/internal/su.go 内部中，对于dae自动使用sudo 来提权对于 linux 桌面端的支持并不是特别完善。
同时方式只有 sudo 方案，对于一些应用程序非 root 运行，需要向 stdin 内部输入 sudo 密码来提权。
同时使用 os.Geteuid 来兼容 setgid.
把 cmd/internal/su.go 内部的提权分为了两部分
- 先尝试使用 桌面端 的组件启动 (pkexec) (主流组件，其他组件例如 kdesu 太老了 没有做适配)
```go
func tryPolkit() (path string, arg []string) {
var possible = []string{"pkexec"}
for _, v := range possible {
path, err := exec.LookPath(v)
if err != nil {
continue
}
if isExistAndExecutable(path) {
switch v {
case "pkexec":
return path, []string{path, "--keep-cwd", "--user", "root"}
}
}
}
return "", nil
}
```
- 再次尝试 sudo 
```go
func trySudo() (path string, arg []string) {
pathSudo, err := exec.LookPath("sudo")
if err != nil || !isExistAndExecutable(pathSudo) {
return "", nil
}
// …
```

feat: enhance privilege elevation logic

---

go.mod
go.sum

https://github.com/daeuniverse/outbound/pull/30

fix(trojan): websocket path loss

---

component/routing/function_parser.go

#736 
- truncate the process name to 15 characters(previously 16)
- issue the truncation info log whenever the process name is longer than 15 characters(previously 16)
#736 
#474 
Closes #_[736]_
add pname(systemd-resolved) -> must_direct
then all the dns traffic through systemd-resolved goes out directly
but before the PR, it doesn't.
I test the patch on main branch, because on develop branch dae errors out **without this patch** as 
```
load eBPF objects: field TproxyLanEgress: program tproxy_lan_egress: load program: permission denied: misaligned stack access off
```

fix(config): correct the truncation of process name(comm name)

---

control/kern/tproxy.c

Previously, the wan interface had implemented udp conntrack
This PR implemented udp conntrack for lan interface.
- Implement udp conntrack for lan interface.
You can use those python codes for testing, 
Try to initiate a request from wan to lan. You should be able to observe that DAE skips the packet instead of routing it.
You could try to have reply packets routed to a node and observe whether `dae0` has the reply packet.
server:
```python
import socket
def udp_server(host='::', port=12345):
"""A UDP server supporting IPv6 and proper cleanup."""
server_socket = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
try:
server_socket.bind((host, port))
print(f"UDP server listening on [{host}]:{port}")
while True:
message, client_address = server_socket.recvfrom(1024)  # Buffer size 1024 bytes …
```

feat: udp conntrack for lan interface

---

component/interface_manager.go
control/control_plane.go
control/control_plane_core.go

https://github.com/daeuniverse/dae/issues/724
该PR抽象了lazybind的能力以便后续其他功能使用（主要是后续在routing中过滤interface需要）
该PR实现的功能与 #729 类似
此外，为wan也加入了lazybind
- interface name now support wildcard
- wan interface now support lazybind
Closes #724
Closes #729

feat(config): wildcard interface name support & refactor lazybind

---

.github/workflows/bpf-test.yml
component/routing/function_parser.go
control/kern/tproxy.c

之前为了修复 #736, #738 相当于把 dae pname 缩减到 15 字节了，但稍作修改也可让 dae 正确匹配 16 字节 pname。
核心 bug 出在 bpf_core_read_str (bpf_probe_read_user_str)，内核的实现是强行在最后一个字节设为 \0：
```c
long strncpy_from_user_nofault(char *dst, const void __user *unsafe_addr,
long count)
{
long ret;
if (unlikely(count <= 0))
return 0;
pagefault_disable();
ret = strncpy_from_user(dst, unsafe_addr, count);
pagefault_enable();
if (ret >= count) {
ret = count;
dst[ret - 1] = '\0';
} else if (ret > 0) {
ret++;
}
return ret;
}
```
https://elixir.bootlin.com/linux/v6.6/source/mm/maccess.c#L177
解决办法就是不用 bpf_probe_read_user_str，两处内存都在 bpf 内核态栈里，手动拷贝一下就行了。不能直接用 __builtin_memcpy 是因为 verifier 要安全检查，手动 for 循环里加上 `if (ctx.l + i < MAX_ARG_LEN)` ~~糊弄一下~~ 即可。
（性能也应该更快一点点点）

fix(bpf): Match pname as long as 16 bytes

---

control/kern/tproxy.c

clang-18+ 会导致 verifier 挂掉 #769, 这个 PR 把 `get_real_comm_ctx.l` 的长度从 u32 缩减为 u8 解决了这个问题。业务逻辑上看，get_real_comm_ctx.l 最多存储的 offset 不超过 MAX_ARG_LEN=128，所以 u8 max=256 足够了。
虽然缩减了结构体字段大小，但是内存对齐的原因让结构体整体实际大小没有变化，依然是 16 字节，产生了空洞，但是问题不大，用 `struct get_real_comm_ctx ctx = {}` 保证空洞也被零值化就行了。
测试：
```shell
for v in 12 13 14 15 16 17 18 19; do sudo CLANG=clang-$v make ebpf-test; done
```

fix(bpf): Make bpf code compatible with clang-12 to clang-19

---

docs/en/README.md
docs/zh/README.md

The original package name `dae-bin-x64-v3` is ill-formed, which makes it removed from AUR. Therefore, it has been renamed to `dae-avx2-bin`.
Related commit: https://github.com/archlinuxcn/repo/commit/b272d171daa6b6bba845b6bf46c373c39e52e6d4
- Update package name of the AVX2-optimized binary package in archlinuxcn section of installation guide
- Add AVX2-optimized binary package to AUR section in installation guide

docs: update archlinuxcn package name & add AVX2 package to AUR

---

.github/workflows/bpf-test.yml

Dae users tend to prefer building Dae from source rather than downloading pre-built binaries. Let’s ensure that all LLVM versions are properly managed by CI.

ci(bpf-test): Test bpf against llvm 15-19

---

control/dns_control.go
control/udp_task_pool.go
control/udp_task_pool_test.go
go.mod
go.sum

1. Fixed the regression introduced by #649
2. Refactor udp_task_pool to avoid `EmitTask` stuck or task loss or incorrect task run order

fix: solve the problem that DNS dialer not perform switching & udp traffic stucks

---

control/bpf_utils.go
control/control_plane_core.go
control/kern/tproxy.c

删掉了 bpf 里不再被使用的代码，无业务逻辑改动。
两点需要额外关注：
1. 删掉了 `#if __clang_major__ >= 10` ，我们最低的 clang 都是 15，不存在低于 10 的。
2. 删掉了 ifindex_params_map 和用户态的 map update，所以要手动定义一个 bpfIfParams struct 给用户态做 NIC feature check. 所以也节约了一点点点 cpu memory...

chore(bpf): Cleanup dead bpf code

---

common/consts/ebpf.go
control/control_plane_core.go
control/kern/tests/bpf_test.c
control/kern/tproxy.c

这样可以干掉 linklen_map，降低四个 tc hooks 的指令数，节省每个 skb 处理所需的 cpu。

optimize(bpf): Load separate programs for L2/L3 netdev

---

docs/en/user-guide/run-as-daemon.md

* fix "permissions 0644 for '/etc/dae/config.dae' are too open"
* fix wrong release page link.
-  docs(user-guide): fix missing `chmod` after downloaded the sample config file and fix the link of release page

docs(user-guide): fix missing `chmod`  after downloaded the sample config file and fix the link of release page
