daeuniverse/dae

README.md

docs: add ip-forwarding guide

---

.github/workflows/release.yml

ci: remove unnecessary deps

---

docs/getting-started/README.md
docs/getting-started/run-as-daemon.md

doc: add run-as-daemon.md

---

example.dae

patch: provide alternative tcp healthcheck url

---

CHANGELOGS.md

chore: add changelogs

---

CHANGELOGS.md

chore: update changelogs

---

.pre-commit-config.yaml
docs/contribute.md

- chore: add pre-commit-hook
- doc(contribute): add pre-commit setup guide
- chore(pre-commit): add custom gofmt hook
```console
◆ dae git:(pre-commit-hook) ✗ ❯❯❯ lazygit                                                                                                                                           22:41:39
+ bash -c git commit -m "test"
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check json...........................................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
fix double quoted strings............................(no files to check)Skipped
fix end of …
```

chore: add pre-commit hook

---

CODEOWNERS

chore(codeowner): update ownership

---

go.mod
go.sum

UDP cannot work when using `trojan+grpc`.
Fixed in https://github.com/mzz2017/softwind/commit/98d9a7116d723f4d65a8f75ac0af74109572fba0.

fix(trojan): udp problem

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature-request.md
CHANGELOGS.md

Update changelogs to include release-v0.1.8

chore: update changelogs to include release-v0.1.8

---

.github/workflows/docker.yml

PRs would trigger docker.yml action when the branch has prefix feat and fix, which is unexpected.
Remove docker.yml running on fix* and feat* branches.

fix(ci): PR runs docker action in some cases

---

CHANGELOGS.md
README.md

Release v0.1.10 from v0.1.10rc1

chore: release v0.1.10

---

CHANGELOGS.md
README.md

Release v0.2.0rc1.
1. readme
2. changelog

chore: release v0.2.0rc1

---

CHANGELOGS.md
README.md

Sync CHANGELOGS and README to `main` branch.

chore: release v0.2.0rc1 (#115)

---

go.mod
go.sum

- Upgrade softwind <https://github.com/mzz2017/softwind/commit/86b8bb994aff187f12dbcbacf898f6da89778cc4>

fix(trojan): potential panic due to invalid packet control data

---

CHANGELOGS.md
README.md
go.mod
go.sum

Cherry-pick https://github.com/daeuniverse/dae/pull/120.

chore: release 0.1.10.p1 (patch1)

---

CHANGELOGS.md
README.md

chore: release v0.2.0rc2 (#115)

---

.github/workflows/build.yml
Makefile

https://github.com/daeuniverse/dae/actions/runs/5222582225/jobs/9428252784?pr=128
- Remove `bash` syntax to support `sh`.
- Add `Makefile` to trigger CI.
#126

chore: fix make with /bin/sh

---

config/parser.go

The incorrect behavior is like the image: the first three are default values and the latter are user-given values.
- Clear the default values before setting the user-given values to slices.

fix(config): problem that always append values to default list

---

Dockerfile

Change geodata upstream to <https://github.com/v2rayA/dist-v2ray-rules-dat>

chore(Dockerfile): change geodata upstream

---

.github/PULL_REQUEST_TEMPLATE.md

- chore(pr_template): correct a typo
NA

chore(pr_template): correct a typo

---

CHANGELOGS.md
README.md

Re-release from v0.2.0rc3 and cherry-pick #162.

ci(release): draft release v0.2.0rc4

---

README.md

As the title suggests. In the meanwhile, update badge icon to `:rocket`
- feat: make release-badge updated on the fly
NA

docs(readme/badges): make release-badge updated on the fly

---

docs/en/tutorials/run-on-alpine.md

run-on-alpine.md: Add Alpine Linux guide
Fix #_[issue number]_

docs(run-on-alpine.md)Add Alpine guide

---

control/control_plane.go

This problem deepened since #203. However, this problem exists for a long time.
This PR fixes it.
- Pass in a copy of `oob` into the goroutine instead of reusing it.

fix: No AddrPort presented

---

.github/workflows/build.yml
.github/workflows/daily-build.yml

- ci(build,daily-build.yml): adhere to naming convention
NA

ci(build,daily-build.yml): adhere to naming convention

---

.github/PULL_REQUEST_TEMPLATE.md

- chore(pr_template): add test result section
- fix: fix issue reference keyword
NA
https://github.com/daeuniverse/dae-1/actions/runs/5508370825

chore(pr_template): add test result section

---

.github/workflows/seed-build.yml

Apply some minor patches in #209; fix incompatible build version for `Build (Main)` workflow.
- ci/fix(seed-build): catch non-pr condition
NA
NA

ci/fix(seed-build): catch non-pr condition

---

.github/workflows/pr-build.yml

- ci(pr-build): fix default branch for seed workflow
NA
NA

ci(pr-build): fix default branch for seed workflow

---

.github/workflows/build.yml

Fix the following issue:
- ci(build): add ref input (required)
NA
NA

ci/fix(build): add ref input (required)

---

.gitignore
cmd/run.go
common/consts/ebpf.go
component/outbound/dialer_group_test.go
control/control_plane.go
control/tcp.go
control/udp.go
go.mod
go.sum
pkg/logger/logger.go

- Add arguments: `--logfile` `--logfile-maxbackups` `--logfile-maxsize`.
- Refactor `domain++` code.
- Add a more friendly tip for no-load mode.

feat/chore: add log file/refine code/add tip for no-load

---

.github/workflows/daily-build.yml

As the title suggests. Fix failure build - https://github.com/daeuniverse/dae/actions/runs/5556096079
- ci/fix(daily-build): add missing ref input
NA
NA

ci/fix(daily-build): add missing ref input

---

.github/workflows/seed-build.yml

Add condition to run report-result to make it applicable to `PR Build (Preview)`
- ci/hotfix(seed-build): add condition to run report-result
- patch: add condition to run ONLY for pr-build
NA
NA

ci/hotfix(seed-build): add condition to run report-result

---

.github/workflows/build.yml
.github/workflows/seed-build.yml

Inherit secret for seed-build workflow.
- ci/hotfix(build): inherit secret
- fix(seed-build): refine condition
NA
https://github.com/daeuniverse/dae-1/actions/runs/5566107405/jobs/10166954902

ci/hotfix(build): inherit secret

---

common/subscription/subscription.go

- Add back lost `client.Do(req)`.

hotfix: fix subscription pulling panic caused by #233

---

.github/workflows/generate-changelogs.yml

Reduce confusion.
- ci/fix(generate_changelogs): remove desp for dry_run input
NA
NA

ci/fix(generate_changelogs): remove desp for dry_run input

---

docs/zh/configuration/routing.md

Translated routing docs.
- docs: create zh routing docs
N/A
N/A

docs: create zh routing docs

---

component/outbound/dialer/juicity/juicity.go
component/outbound/outbound.go
docs/en/proxy-protocols.md
docs/zh/proxy-protocols.md
example.dae
go.mod
go.sum

Support [juicity](https://github.com/juicity/juicity).
- Implement [juicity](https://github.com/juicity/juicity).

feat: support juicity

---

.github/PULL_REQUEST_TEMPLATE.md

Update pr_template section headers.

chore(pr_template): update headers

---

cmd/call.go
cmd/honk.go

feat: dae can call now

---

go.mod
go.sum

chore: bump quic-go to v0.38.0

---

docs/en/how-it-works.md

As the title suggests. It is worth mentioning that the task was completed by ChatGPT 3.5
Ref: https://chat.openai.com/share/9fb7d601-2a86-4079-8cdc-3ecdf90cab48

docs(en): update how-it-works

---

common/subscription/subscription.go

chore: close file descriptor & remove duplicated error handle

---

CHANGELOGS.md

- chore(release): add changelogs entry for v0.3.0

chore(release): add changelogs entry for v0.3.0

---

.github/workflows/generate-changelogs.yml

Update default assignee from @daebot to ["yqlbu","mzz2017","kunish"]
- ci(generate-changelogs): update default assignees list

ci(generate-changelogs): update default assignees list

---

component/outbound/dialer/register.go

improve: rm dup code in NewFromLink()

---

Dockerfile

https://github.com/daeuniverse/daed/issues/250
- ci(Dockerfile): upgrade golang and clang (https://github.com/daeuniverse/daed/issues/250)
https://github.com/daeuniverse/daed/issues/250

chore(Dockerfile): upgrade golang and clang (https://github.com/daeuniverse/daed/issues/250)

---

docs/en/README.md
docs/zh/README.md

Installation guide of dae on Arch Linux is not intact.
- Add archlinuxcn installtion source
- Small tweaks

docs: tweak archlinux installation guide

---

README.md

As the title suggests, proposing changes to refine project description. The task was completed by ChatGPT 3.5
- docs(readme): refine project description

docs(readme): refine project description

---

docs/en/user-guide/reload-and-suspend.md

improve docs about reload
docs: improve docs about reload

docs: improve docs about reload

---

cmd/cmd.go
cmd/reload.go
cmd/run.go
cmd/suspend.go
control/control_plane.go

```
dae reload/suspend [pid] [flags]
Flags:
-a, --abort   Abort established connections.
```
- feat: support --abort for reload and suspend

feat: support --abort for reload and suspend

---

go.mod
go.sum

chore: upgrade softwind

---

.github/workflows/kernel-test.yml
control/kern/tproxy.c

bpf: Don't clear checksum on wan_egress

---

.github/workflows/generate-changelogs.yml

- chore(generate-changelogs): update required reviewers list
NA

chore(generate-changelogs): update required reviewers list

---

.github/workflows/check-docs.yml
.github/workflows/docker.yml
.github/workflows/generate-changelogs.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/seed-build.yml
.github/workflows/sync-docs.yml

1. Update actions/checkout@v3 to actions/checkout@v4
2. Remove double extension name in test builds

ci: update actions/checkout@v3 to actions/checkout@v4

---

docs/en/README.md
docs/zh/README.md

The Arch Linux section in Quick Start Guide is incomplete.
-  Add ```dae-git``` & ```dae-bin-x64-v3``` in Arch Linux section of Quick Start Guide

docs: update arch installation

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

- ci: update action-gh-release to v2
- ci: update setup-go to v5 in prerelease ci
- ci: better uploading files

ci: update action-gh-release to v2

---

go.mod
go.sum

当前不支持 userpass 的认证方式，已经在 https://github.com/daeuniverse/outbound/issues/14 修复。
感谢 @xmapst 
Closes https://github.com/daeuniverse/outbound/pull/13

fix/chore(hy2): update outbound submodule to fix userpass auth

---

example.dae

chore(example.dae): add hy2 in comments

---

docs/en/user-guide/persistent-subscription.md

Add curl retry params to avoid failure of fetching subs && Use systemd Restart=on-failure to make sure every subs fetched successfully. 

docs: update persistent script

---

go.mod
go.sum

outbound: https://github.com/daeuniverse/outbound/pull/23

fix(hy2): dialer regression introduced by #645 pr

---

docs/en/configuration/dns.md
docs/zh/configuration/dns.md
example.dae

docs(dns): fix typo

---

config/desc.go

Small PR - Commit e39ec7fc0502bdcfec0c4759cf7954ed0b8034c7 moved bunch of files around. This PR adjusts the sources to changes.

fix: update sources in `desc.go`

---

control/control_plane.go

chore: more detail of Choose DNS path log

---

go.mod
go.sum

https://github.com/daeuniverse/outbound/pull/29

feat(vision): support xudp

---

docs/en/proxy-protocols.md
docs/zh/proxy-protocols.md

#708 已经支持了 xudp docs应该改了
修改docs 文档
no
no need to test

docs: add UDP support for Reality

---

docs/en/README.md
docs/zh/README.md

- `dae` is available on [Fedora Copr](https://copr.fedorainfracloud.org/coprs/zhullyb/v2rayA/package/dae), which is maintained by @zhullyb.
- Add [Fedora Copr](https://copr.fedorainfracloud.org/coprs/zhullyb/v2rayA/package/dae) to installation guide

docs: add Fedora Copr to installation guide

---

go.mod
go.sum

https://github.com/daeuniverse/outbound/pull/33
```
1月 28 16:23:39 CSL-MacBook-Pro daed[910]: goroutine 23791 [running]:
1月 28 16:23:39 CSL-MacBook-Pro daed[910]: github.com/daeuniverse/outbound/transport/grpc.(*ClientConn).Close(0xc00304db00)
1月 28 16:23:39 CSL-MacBook-Pro daed[910]:         github.com/daeuniverse/outbound@v0.0.0-20241203160254-b61700645a6c/transport/grpc/grpc_client.go:169 +0x3a
1月 28 16:23:39 CSL-MacBook-Pro daed[910]: github.com/daeuniverse/outbound/protocol/vmess.(*Conn).Close(0xc0027897e0?)
1月 28 16:23:39 CSL-MacBook-Pro daed[910]:         github.com/daeuniverse/outbound@v0.0.0-20241203160254-b61700645a6c/protocol/vmess/conn.go:80 +0x1b
1月 28 16:23:39 CSL-MacBook-Pro daed[910]: github.com/daeuniverse/dae/control.(*DoTCP).Close(0xc0038e4180?)
1月 28 16:23:39 …
```

fix: close of closed channel

---

.github/workflows/kernel-test.yml

ci(kernel-test.yml): update checkout to v4.2

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

- Zip format for binary archives was removed in #721.
- Add Zip format for binary archives
- Adjust XZ compression level
Tested in my own fork.

ci: add zip format for binary archives & adjust compression level

---

docs/en/tutorials/run-on-centos7.md
docs/en/user-guide/kernel-upgrade.md

- In some documentation, the minimum kernel version hasn't been updated to 5.17.
- Update minimum kernel version in documentation to 5.17.

docs: update minimum kernel version to 5.17

---

cmd/run.go
config/config.go
example.dae

chore(cmd/config): fix typos

---

example.dae

docs(example): add fallback resolver

---

.github/workflows/kernel-test.yml

Update 6.1 and 6.6 kernel versions, add 6.12 kernel (one of the LTS versions).

test(ci/kernel-test): Update kernels in ci

---

control/kern/tproxy.c

fix(tproxy): refactor parse_transport and fix wrong ipv6 extension header offset calc
在原先的代码中，在解析ipv6 extension header时，错误理解了第二个byte中的长度值，这个长度值不包括ipv6 extension header本身的固定长度（8 byte），并且这个数字是按8对其的，需要将(ext_len + 1)*8才是header的完整长度
因此在原先的代码中，包含ipv6 extension的包，其实无法正确解析payload
https://datatracker.ietf.org/doc/html/rfc2460#section-4.2
此外重构了parse_transport的代码, 优化掉了冗长的handle_ipv6_extensions, 减少代码量提高可读性

fix(tproxy): refactor parse_transport and fix wrong ipv6 extension header offset calc

---

control/kern/tproxy.c

We used bpf_timer wrong way. It should have been as simple as rearming the existing timer instead of re-initiating a timer.
Let's see if this patch can fix kernel panic.
Closes #843

fix(bpf): Fix bpf timer

---

component/outbound/outbound.go
go.mod
go.sum

https://github.com/daeuniverse/outbound/pull/46

feat(anytls): support anytls tcp&&udp

---

config/config.go
control/control_plane.go
control/dns_control.go
control/dns_listener.go
docs/en/configuration/dns.md
docs/zh/configuration/dns.md
example.dae

feat(dns): support dns bind to local port
feat(dns): support dns bind to local port

feat(dns): support dns bind to local port
